config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resource :authentication, only: [:new, :create, :destroy]
  resources :moves, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :places, only: [:index, :new, :edit, :create, :update]
  match "responses/:id", to: "responses#show", via: [:get, :post], as: :response
  resource :user, only: [:new, :create, :show, :edit, :update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/_signed_in_index.html.erb
<div class="jumbotron">
  <h1>Hello <%= current_user %>!</h1>
  <% if current_place %>
    <p>
      You’re currently in
      <%= link_to current_place, edit_place_path(current_place) %>
      and calls are being forwarded to
      <strong><%= current_place.phone_number %></strong>.
    </p>
    <p>
      Your unique
      <%= link_to "Twilio", "https://www.twilio.com/" %>
      request URL is <br />
      <%= link_to response_url(current_user.uuid), response_url(current_user.uuid) %>
    </p>
    <p>
      Edit your <%= link_to "places", places_path %>
      and <%= link_to "travel", moves_path %>.
    </p>
  <% else %>
    <p>
      Add some <%= link_to "places", places_path %>
      and <%= link_to "travel", moves_path %>.
    </p>
  <% end %>
</div>

app/views/home/_signed_out_index.html.erb
<div class="jumbotron">
  <h1>Hello!</h1>
  <p>
    <strong><%= app_name %></strong> makes it easy for people to get in touch with
    you, no matter where you travel.
  </p>
  <p>
    How it works:
  </p>
  <ol>
    <li>Set up the places you travel to, and your contact number in each.</li>
    <li>Add your travel itinerary by saying when you’ll arrive in a place.</li>
    <li>Point a <%= link_to "Twilio", "https://www.twilio.com/" %> phone number
      at your unique call flow URL.
    </li>
    <li>Phone calls follow you around the world as if by magic!</li>
  </ol>

  <p>
    <%= link_to "Sign in", new_authentication_path %> or
    <%= link_to "sign up", new_user_path %> to get started.
  </p>
</div>

app/views/home/index.html.erb
<% if current_user %>
  <%= render partial: "signed_in_index" %>
<% else %>
  <%= render partial: "signed_out_index" %>
<% end %>