config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resource :authentication, only: [:new, :create, :destroy]
  resources :moves, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :places, only: [:index, :new, :edit, :create, :update]
  match "responses/:id", to: "responses#show", via: [:get, :post], as: :response
  resource :user, only: [:new, :create, :show, :edit, :update]
end

app/models/move.rb
require "forwardable"

class Move < ActiveRecord::Base
  extend Forwardable
  belongs_to :user
  belongs_to :place
  validates :user, presence: true
  validates :place, presence: true
  validates :year, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 2000,
    less_than_or_equal_to: 2100
  }
  validates :month, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 12
  }
  validates :mday, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 31
  }
  validates :hour, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 23
  }
  validates :minute, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 59
  }

  validate do |move|
    unless place.user == move.user
      move.errors.add(:base, "Invalid place")
    end
  end


  def_delegator :place, :name, :place_name

  before_save :compute_timestamp

  def self.chronologically
    order(timestamp: :asc)
  end

  def self.current_place(now = Time.now)
    move = order(timestamp: :desc).
      where(arel_table[:timestamp].lteq(now.to_i)).
      first
    move && move.place
  end

  def date=(ymd)
    if (m = ymd.match(/\A(\d{4})-(\d{2})-(\d{2})\z/))
      self.year, self.month, self.mday = [1, 2, 3].map { |i| m[i].to_i }
    end
  end

  def date
    "%04d-%02d-%02d" % [year, month, mday]
  end

  def time=(hm)
    if (m = hm.match(/\A(\d{2}):(\d{2})\z/))
      self.hour, self.minute = [1, 2, 3].map { |i| m[i].to_i }
    end
  end

  def time
    "%02d:%02d" % [hour, minute]
  end

  def local_date_string
    "#{date} #{time}"
  end

  def utc_date_string
    u = self.utc
    "%04d-%02d-%02d %02d:%02d" % [u.year, u.month, u.mday, u.hour, u.minute]
  end

  def utc
    place.utc(year, month, mday, hour, minute)
  end

  def compute_timestamp
    self.timestamp = self.utc.to_i
  end

  def timestamp
    read_attribute(:timestamp) || compute_timestamp
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :require_current_user
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  def index
    @moves = moves.chronologically
  end

  # GET /moves/new
  def new
    @move = moves.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  def create
    @move = moves.new(move_params)

    if @move.save
      redirect_to moves_path, notice: 'Move was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /moves/1
  def update
    if @move.update(move_params)
      redirect_to moves_path, notice: 'Move was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /moves/1
  def destroy
    @move.destroy
    redirect_to moves_path, notice: 'Move was successfully destroyed.'
  end

private
  def moves
    @current_user.moves
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_move
    @move = moves.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def move_params
    params.require(:move).permit(:user_id, :place_id, :year, :month, :mday, :hour, :minute)
  end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= simple_form_for(@move) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :place, collection: current_user.places, label: "Destination" %>
    <p><%= link_to "Add a new place", new_place_path %> if necessary.</p>
    <%= f.input :year, collection: (Time.now.year - 10 .. Time.now.year + 10) %>
    <%= f.input :month, collection: (1 .. 12) %>
    <%= f.input :mday, collection: (1 .. 31) %>
    <%= f.input :hour, collection: (0 .. 24) %>
    <%= f.input :minute, collection: [0, 15, 30, 45] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing travel</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Travel</h1>

<table class="table">
  <thead>
    <tr>
      <th>Place</th>
      <th>Arrival time at destination</th>
      <th>Time in UTC</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.place %></td>
        <td><%= move.local_date_string %></td>
        <td><%= move.utc_date_string %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Delete', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add travel', new_move_path %>

app/views/moves/new.html.erb
<h1>New travel</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>