config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resource :authentication, only: [:new, :create, :destroy]
  resources :moves, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :places, only: [:index, :new, :edit, :create, :update]
  match "responses/:id", to: "responses#show", via: [:get, :post], as: :response
  resource :user, only: [:new, :create, :show, :edit, :update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_place

protected
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_place
    current_user && current_user.current_place
  end

  def require_current_user
    redirect_to new_authentication_path unless current_user
  end

  def redirect_by_goal
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    "Stay in touch"
  end
end

app/views/application/_footer.html.erb
<div id="footer">
  <div class="container">
    <strong><%= app_name %></strong> is not even alpha software, is not
    guaranteed to work, and probably should not be used by anybody.
    It is not affiliated with Twilio, Inc., in any way.
    Made by <%= link_to "Paul Battley", "http://po-ru.com/" %>.
    <%= link_to "Source code", "https://bitbucket.org/threedaymonk/stayintouch" %>.
  </div>
</div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= app_name %></a>
    </div>

    <div>
      <% if current_user %>
        <%= render partial: "signed_in_nav" %>
      <% else %>
        <%= render partial: "signed_out_nav" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_signed_in_nav.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Places", places_path %></li>
  <li><%= link_to "Travel", moves_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to current_user, edit_user_path %></li>
  <li><%= button_to("Sign out", authentication_path, method: :delete, class: "btn") %></li>
</ul>

app/views/application/_signed_out_nav.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to("Sign in", new_authentication_path) %></li>
</ul>