config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resource :authentication, only: [:new, :create, :destroy]
  resources :moves, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :places, only: [:index, :new, :edit, :create, :update]
  match "responses/:id", to: "responses#show", via: [:get, :post], as: :response
  resource :user, only: [:new, :create, :show, :edit, :update]
end

app/models/place.rb
require "tzinfo"

class Place < ActiveRecord::Base
  def self.zone_identifiers
    TZInfo::Timezone.all_country_zone_identifiers.sort
  end

  validates_inclusion_of :tz_name, in: zone_identifiers
  validates_format_of :phone_number, with: /\A\+[0-9\-. ()]+\z/
  belongs_to :user
  has_many :moves

  def self.alphabetically
    order(name: :asc)
  end

  def utc(year, month, mday, hour, minute, second = 0)
    TZInfo::Timezone.get(tz_name).local_to_utc(
      DateTime.new(year, month, mday, hour, minute, second))
  end

  def to_s
    [name, tz_name].reject(&:blank?).first
  end

  def after_save
    moves.each do |move|
      move.compute_timestamp
      move.save
    end
  end

  def normalized_phone_number
    phone_number.gsub(/[^\+0-9]/, "")
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_current_user
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  def index
    @places = places.alphabetically
  end

  # GET /places/new
  def new
    @place = places.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = places.new(place_params)

    if @place.save
      redirect_to places_url, notice: 'Place was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to places_url, notice: 'Place was successfully updated.'
    else
      render :edit
    end
  end

private
  def places
    @current_user.places
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = places.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def place_params
    params.require(:place).permit(:name, :tz_name, :phone_number)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, as: :string %>
    <%= f.input :tz_name, collection: Place.zone_identifiers %>
    <%= f.input :phone_number, as: :string %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Time zone</th>
      <th>Phone number</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.tz_name %></td>
        <td><%= place.phone_number %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>